name: CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up java env
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: "18.0.0+36"
          cache: 'maven'          
      - run: chmod +x gradlew
      - name: build action
        run: ./gradlew build